"""baseline schema

The starting point for versioned migrations (FLEDGE Phase 8). Before this, the
schema was created by ``Base.metadata.create_all()`` on every app boot, which
only ever creates *missing* tables — it silently ignores changes to existing
ones, so any model change after the first deploy would never reach the database.

Autogenerated against an empty database and verified two ways: ``alembic check``
reports no drift from the models, and a ``pg_dump --schema-only`` of a database
built by this migration is byte-identical to one built by ``create_all``.

Existing deployments should be stamped rather than upgraded::

    alembic -c backend/alembic.ini stamp 25d65b9ab024

Revision ID: 25d65b9ab024
Revises:
Create Date: 2026-07-24 20:40:12.189813+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '25d65b9ab024'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(), nullable=False),
    sa.Column('genus', sa.String(), nullable=False),
    sa.Column('species_name', sa.String(), nullable=False),
    sa.Column('order_name', sa.String(), nullable=True),
    sa.Column('wiki_url', sa.String(), nullable=True),
    sa.Column('palette', sa.String(), nullable=True),
    sa.Column('silhouette', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('common_name', 'genus', 'species_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.Column('notify_sms', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('classification_tier', sa.String(), nullable=False),
    sa.Column('feed_type', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('battery', sa.Float(), nullable=True),
    sa.Column('signal', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiet_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('notify_new_species_only', sa.Boolean(), nullable=False),
    sa.Column('default_tier', sa.String(), nullable=False),
    sa.Column('escalation_threshold', sa.Integer(), nullable=False),
    sa.Column('debounce_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('device_users',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('device_id', 'user_id')
    )
    op.create_table('sightings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=True),
    sa.Column('video_data', sa.LargeBinary(), nullable=True),
    sa.Column('classification_tier_used', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('weather_conditions', sa.String(), nullable=True),
    sa.Column('delayed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    op.drop_table('sightings')
    op.drop_table('device_users')
    op.drop_table('user_preferences')
    op.drop_table('devices')
    op.drop_table('users')
    op.drop_table('species')
